<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class FootballTeamSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $teams = [
            'Afghanistan',
            'Albania',
            'Algeria',
            'Andorra',
            'Angola',
            'Antigua and Barbuda',
            'Argentina',
            'Armenia',
            'Australia',
            'Austria',
            'Azerbaijan',
            'Bahamas',
            'Bahrain',
            'Barbados',
            'Belarus',
            'Belize',
            'Benin',
            'Bhutan',
            'Bolivia',
            'Bosnia and Herzegovina',
            'Botswana',
            'Brazil',
            // 'Brunei',
            // 'Bulgaria',
            // 'Burkina Faso',
            // 'Burundi',
            // 'Cambodia',
            // 'Cameroon',
            // 'Cape Verde',
            // 'Central African Republic',
            // 'Chad',
            // 'Chile',
            // 'China PR',
            // 'Chinese Taipei',
            // 'Colombia',
            // 'Comoros',
            // 'Congo',
            // 'Congo DR',
            // 'Cook Islands',
            // 'Costa Rica',
            // 'Côte d’Ivoire',
            // 'Croatia',
            // 'Cuba',
            // 'Curaçao',
            // 'Cyprus',
            // 'Czech Republic',
            // 'Denmark',
            // 'Djibouti',
            // 'Dominica',
            // 'Dominican Republic',
            // 'Ecuador',
            // 'Egypt',
            // 'El Salvador',
            // 'Equatorial Guinea',
            // 'Eritrea',
            // 'Estonia',
            // 'Eswatini',
            // 'Ethiopia',
            // 'Faroe Islands',
            // 'Fiji',
            // 'Finland',
            // 'France',
            // 'Gabon',
            // 'Gambia',
            // 'Georgia',
            // 'Germany',
            // 'Ghana',
            // 'Gibraltar',
            // 'Greece',
            // 'Grenada',
            // 'Guam',
            // 'Guatemala',
            // 'Guinea',
            // 'Guinea-Bissau',
            // 'Guyana',
            // 'Haiti',
            // 'Honduras',
            // 'Hong Kong',
            // 'Hungary',
            // 'Iceland',
            // 'Indonesia',
            // 'Iran',
            // 'Iraq',
            // 'Israel',
            // 'Italy',
            // 'Jamaica',
            // 'Japan',
            // 'Jordan',
            // 'Kazakhstan',
            // 'Kenya',
            // 'Kiribati',
            // 'Korea DPR',
            // 'Korea Republic',
            // 'Kosovo',
            // 'Kuwait',
            // 'Kyrgyzstan',
            // 'Laos',
            // 'Latvia',
            // 'Lebanon',
            // 'Lesotho',
            // 'Liberia',
            // 'Libya',
            // 'Liechtenstein',
            // 'Lithuania',
            // 'Luxembourg',
            // 'Macao',
            // 'Madagascar',
            // 'Malawi',
            // 'Malaysia',
            // 'Maldives',
            // 'Mali',
            // 'Malta',
            // 'Marshall Islands',
            // 'Martinique',
            // 'Mauritania',
            // 'Mauritius',
            // 'Mexico',
            // 'Micronesia',
            // 'Moldova',
            // 'Monaco',
            // 'Mongolia',
            // 'Montenegro',
            // 'Morocco',
            // 'Mozambique',
            // 'Myanmar',
            // 'Namibia',
            // 'Nauru',
            // 'Nepal',
            // 'New Caledonia',
            // 'New Zealand',
            // 'Nicaragua',
            // 'Niger',
            // 'Nigeria',
            // 'Niue',
            // 'North Macedonia',
            // 'Northern Mariana Islands',
            // 'Norway',
            // 'Oman',
            // 'Pakistan',
            // 'Palau',
            // 'Palestine',
            // 'Panama',
            // 'Papua New Guinea',
            // 'Paraguay',
            // 'Peru',
            // 'Philippines',
            // 'Poland',
            // 'Portugal',
            // 'Puerto Rico',
            // 'Qatar',
            // 'Reunion',
            // 'Romania',
            // 'Russia',
            // 'Rwanda',
            // 'Saint Kitts and Nevis',
            // 'Saint Lucia',
            // 'Saint Vincent and the Grenadines',
            // 'Samoa',
            // 'San Marino',
            // 'São Tomé and Príncipe',
            // 'Saudi Arabia',
            // 'Senegal',
            // 'Serbia',
            // 'Seychelles',
            // 'Sierra Leone',
            // 'Singapore',
            // 'Slovakia',
            // 'Slovenia',
            // 'Solomon Islands',
            // 'Somalia',
            // 'South Africa',
            // 'South Sudan',
            // 'Spain',
            // 'Sri Lanka',
            // 'Sudan',
            // 'Suriname',
            // 'Sweden',
            // 'Switzerland',
            // 'Syria',
            // 'Tahiti',
            // 'Tajikistan',
            // 'Tanzania',
            // 'Thailand',
            // 'Timor-Leste',
        ];

        foreach ($teams as $team) {
            DB::table('football_teams')->insert([
                'team_name' => $team,
                'man_team_points' => rand(50, 2000),
                'women_team_points' => rand(50, 2000),
            ]);
        }
    }
}
