<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    public function run()
    {
        User::create([
            'name'              => 'Mahira Khan',
            'phone'              => '01811000000',
            'email'             => 'superadmin@gmail.com',
            'email_verified_at' => now(),
            'password'          => Hash::make('Shahed1@'),
            'remember_token'    => Str::random(10),
            'role_id'           => 1,
            'date_of_birth'     => '2022-09-07',
            'image_id'          => 1,
            'designation_id'    => rand(1, 5),
            'permissions' => [
                'dashboard_read',
                'user_read',
                'user_create',
                'user_update',
                'user_delete',
                'role_read',
                'role_create',
                'role_update',
                'role_delete',
                'language_read',
                'language_create',
                'language_update',
                'language_update_terms',
                'language_delete',
                'general_settings_read',
                'general_settings_update',
                'storage_settings_read',
                'storage_settings_update',
                'recaptcha_settings_read',
                'recaptcha_settings_update',
                'email_settings_read',
                'email_settings_update',
                'team_read',
                'team_create',
                'team_update',
                'team_delete',
                'player_read',
                'player_create',
                'player_update',
                'player_delete',
                'matchh_read',
                'matchh_create',
                'matchh_update',
                'matchh_delete',
                'scoreupdates_read',
                'scoreupdates_create',
                'scoreupdates_update',
                'scoreupdates_delete',
                'updatebowler_read',
                'updatebowler_create',
                'updatebowler_update',
                'updatebowler_delete',
                'score_read',
                'score_create',
                'score_update',
                'score_delete',
                'scorebowlerfirst_read',
                'scorebowlerfirst_create',
                'scorebowlerfirst_update',
                'scorebowlerfirst_delete',
                'scorebattersecond_read',
                'scorebattersecond_create',
                'scorebattersecond_update',
                'scorebattersecond_delete',
                'scorebowlersecond_read',
                'scorebowlersecond_create',
                'scorebowlersecond_update',
                'scorebowlersecond_delete',
                'commentrycreate_read',
                'commentrycreate_create',
                'commentrycreate_update',
                'commentrycreate_delete',
                'commentry_read',
                'commentry_create',
                'commentry_update',
                'commentry_delete',
                'managepublictable_read',
                'managepublictable_store',
                'managepublictable_update',
                'managepublictable_delete',
                'point_read',
                'point_store',
                'point_update',
                'point_delete',
                'ranking_read',
                'ranking_store',
                'ranking_update',
                'ranking_delete',
                'series_read',
                'series_store',
                'series_update',
                'series_delete',
                'news_read',
                'news_store',
                'news_update',
                'news_delete',
                'football_team_read',
                'football_team_create',
                'football_team_update',
                'football_team_delete',
                'football_players_read',
                'football_players_create',
                'football_players_update',
                'football_players_delete',
                'goal_scores_read',
                'goal_scores_create',
                'goal_scores_update',
                'goal_scores_delete',
                'football_matchs_read',
                'football_matchs_create',
                'football_matchs_update',
                'football_matchs_delete',
                'football_scores_read',
                'football_scores_create',
                'football_scores_update',
                'football_scores_delete',
                'leagues_read',
                'leagues_create',
                'leagues_update',
                'leagues_delete',
                'footballrankings_read',
                'footballrankings_create',
                'footballrankings_update',
                'footballrankings_delete',
            ],
        ]);

        User::create([
            'name'              => 'Faye Clether',
            'phone'              => '01811000001',
            'email'             => 'admin@gmail.com',
            'email_verified_at' => now(),
            'password'          => Hash::make('Shahed1@'),
            'remember_token'    => Str::random(10),
            'role_id'           => 2,
            'date_of_birth'     => '2022-09-07',
            'image_id'          => 2,
            'designation_id'    => rand(1, 5),
            'permissions' => [
                'user_read',
                'user_create',
                'user_update',
                'user_delete',
                'role_read',
                'role_create',
                'role_update',
                'role_delete',
                'language_read',
                'language_create',
                'language_update_terms',
                'general_settings_read',
                'general_settings_update',
                'storage_settings_read',
                'storage_settings_read',
                'recaptcha_settings_update',
                'email_settings_read',
            ],
        ]);

        User::create([
            'name'              => 'Anna Littlical',
            'phone'              => '01811000002',
            'email'             => 'manager@gmail.com',
            'email_verified_at' => now(),
            'password'          => Hash::make('Shahed1@'),
            'remember_token'    => Str::random(10),
            'role_id'           => 3,
            'date_of_birth'     => '2022-09-07',
            'image_id'          => 3,
            'designation_id'    => rand(1, 5),
            'permissions' => [
                'user_read',
                'user_create',
                'role_read',
                'language_read',
                'language_create',
                'general_settings_read',
                'storage_settings_read',
                'recaptcha_settings_read',
                'email_settings_read',
            ],
        ]);

        for ($i = 0; $i <= 30; $i++) {

            User::create([
                'name'              =>  'Al Annon ' . $i,
                'phone'              =>  '134578978456' . $i,
                'email'             => 'user' . $i . '@gmail.com',
                'email_verified_at' => now(),
                'password'          => Hash::make('Shahed1@'),
                'remember_token'    => Str::random(10),
                'role_id'           => 4,
                'date_of_birth'     => '2022-09-07',
                'image_id'          => 4,
                'designation_id'    => rand(1, 5),
                'permissions' => [
                    'user_read',
                    'role_read',
                    'language_read',
                ],
            ]);
        }
    }
}
